name: Host a new release of the frontend

on:
  release:
    types:
      - published

jobs:
  release:
    name: Build and deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: ssh into machine, and clone repo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/clones
            cd chrono-temp-frontend-prod
            git reset --hard HEAD
            git pull
            docker compose down
            docker compose up --build -d
